-- MySQL Script generated by MySQL Workbench
-- Thu Dec  8 21:08:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`financial_transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`financial_transaction` (
  `id` INT NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  `recurrent` TINYINT NOT NULL,
  `start_date` DATE NOT NULL,
  `completed_at` DATE NOT NULL,
  `essential` TINYINT NOT NULL,
  `is_expense` TINYINT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `financial_transaction_fk_1_idx` (`id_user` ASC),
  CONSTRAINT `financial_transaction_fk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`food` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `food_fk_1_idx` (`id_user` ASC),
  CONSTRAINT `food_fk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`meal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`meal` (
  `id` INT NOT NULL,
  `hour` TIME NOT NULL,
  `date` DATE NOT NULL,
  `consumed_at` DATETIME NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `meal_fk_1_idx` (`id_user` ASC),
  CONSTRAINT `meal_fk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`meal_food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`meal_food` (
  `id` INT NOT NULL,
  `id_meal` INT NOT NULL,
  `id_food` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `meal_food_fk_1_idx` (`id_meal` ASC),
  INDEX `meal_food_fk_2_idx` (`id_food` ASC),
  CONSTRAINT `meal_food_fk_1`
    FOREIGN KEY (`id_meal`)
    REFERENCES `mydb`.`meal` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `meal_food_fk_2`
    FOREIGN KEY (`id_food`)
    REFERENCES `mydb`.`food` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mood`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mood` (
  `id` INT NOT NULL,
  `date` DATE NOT NULL,
  `mood_level` ENUM("AMAZING", "FINE", "OK", "BAD", "AWFUL") NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `mood_fk_1_idx` (`id_user` ASC),
  CONSTRAINT `mood_fk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`custom_repetation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`custom_repetation` (
  `id` INT NOT NULL,
  `occurrences_number` INT NOT NULL,
  `every` INT NOT NULL,
  `week_days` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schedule_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schedule_time` (
  `id` INT NOT NULL,
  `start_date` VARCHAR(45) NOT NULL,
  `end_date` VARCHAR(45) NOT NULL,
  `has_repetition` TINYINT NOT NULL,
  `repetition_type` ENUM("DAILY", "WEEKLY", "MONTHLY", "YEARLY") NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `id_custom_repetation` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `schedule_time_fk_1_idx` (`id_custom_repetation` ASC),
  CONSTRAINT `schedule_time_fk_1`
    FOREIGN KEY (`id_custom_repetation`)
    REFERENCES `mydb`.`custom_repetation` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`to_do`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`to_do` (
  `id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `estimated_time` VARCHAR(255) NOT NULL,
  `deadline` DATETIME NOT NULL,
  `priority` ENUM("HIGH", "MEDIUM", "LOW") NOT NULL,
  `completed_at` DATETIME NULL,
  `id_user` INT NOT NULL,
  `id_schedule_time` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `to_do_fk_1_idx` (`id_user` ASC),
  INDEX `to_do_fk_2_idx` (`id_schedule_time` ASC),
  CONSTRAINT `to_do_fk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `to_do_fk_2`
    FOREIGN KEY (`id_schedule_time`)
    REFERENCES `mydb`.`schedule_time` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sleep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sleep` (
  `id` INT NOT NULL,
  `sleep_goal` FLOAT NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `sleep_fk_1_idx` (`id_user` ASC),
  CONSTRAINT `sleep_fk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`water`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`water` (
  `id` INT NOT NULL,
  `amount_in_day` FLOAT NOT NULL,
  `amount_at_time` FLOAT NOT NULL,
  `id_sleep` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `water_fk_1_idx` (`id_user` ASC),
  INDEX `water_fk_2_idx` (`id_sleep` ASC),
  CONSTRAINT `water_fk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `water_fk_2`
    FOREIGN KEY (`id_sleep`)
    REFERENCES `mydb`.`sleep` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consumed_water`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consumed_water` (
  `id` INT NOT NULL,
  `consumed_at` DATETIME NOT NULL,
  `amount` FLOAT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `consumed_water_fk_1_idx` (`id_user` ASC),
  CONSTRAINT `consumed_water_fk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sleepy_day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sleepy_day` (
  `id` INT NOT NULL,
  `start_datetime` DATETIME NOT NULL,
  `end_datetime` DATETIME NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `sleepy_day_fk_1_idx` (`id_user` ASC),
  CONSTRAINT `sleepy_day_fk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`menstrual_cycle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`menstrual_cycle` (
  `id` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `flow` ENUM("HIGH", "MEDIUM", "LOW") NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `menstrual_cycle_fk_1_idx` (`id_user` ASC),
  CONSTRAINT `menstrual_cycle_fk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`symptoms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`symptoms` (
  `id` INT NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  `id_menstrual_cycle` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `symptoms_fk_1_idx` (`id_menstrual_cycle` ASC),
  CONSTRAINT `symptoms_fk_1`
    FOREIGN KEY (`id_menstrual_cycle`)
    REFERENCES `mydb`.`menstrual_cycle` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`goals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`goals` (
  `id` INT NOT NULL,
  `description` VARCHAR(255) NULL,
  `title` VARCHAR(45) NOT NULL,
  `deadline` DATE NOT NULL,
  `completed_at` DATE NULL,
  `created_at` DATE NOT NULL,
  `progress` INT NOT NULL DEFAULT 0,
  `notification_frequency` ENUM("DAILY", "WEEKLY", "MONTHLY") NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `goals_fk_1_idx` (`id_user` ASC),
  CONSTRAINT `goals_fk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`workout_routines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`workout_routines` (
  `id` INT NOT NULL,
  `sets` INT NOT NULL,
  `muscle_group` VARCHAR(255) NOT NULL,
  `reps` INT NOT NULL,
  `exercise` VARCHAR(255) NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `workout_routines_fk_1_idx` (`id_user` ASC),
  CONSTRAINT `workout_routines_fk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`workout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`workout` (
  `id` INT NOT NULL,
  `date` DATE NOT NULL,
  `is_completed` TINYINT NOT NULL DEFAULT 0,
  `id_user` INT NOT NULL,
  `id_workout_routine` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `workout_fk_1_idx` (`id_user` ASC),
  INDEX `workout_fk_2_idx` (`id_workout_routine` ASC),
  CONSTRAINT `workout_fk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `workout_fk_2`
    FOREIGN KEY (`id_workout_routine`)
    REFERENCES `mydb`.`workout_routines` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
